﻿# Äá»i tÃªn file thÃ nh application.properties náº¿u Äang lÃ  .yml
spring.application.name=api

# Database configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=MotelManagement;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Jackson configuration - Convert camelCase to snake_case
spring.jackson.property-naming-strategy=SNAKE_CASE
