services:
  db:
    image: mysql:8.0
    container_name: room_db
    restart: always
    environment:
      MYSQL_DATABASE: MotelManagement
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    
  backend:
    build: ./backend/api
    image: vinhcute22/room-backend:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/MotelManagement?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    depends_on:
      - db
      
  frontend:
    image: vinhcute22/room-frontend:latest
    container_name: room_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    
volumes:
  mysql_data:
